(package "trinary" "1.0.0" "Trinary logic.")

(website-url "https://github.com/emacs-elsa/trinary-logic")
(keywords "languages")

(package-file "trinary.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'melpa)
(source 'gnu)

(development
 (depends-on "dash")
 (depends-on "elsa")
 (depends-on "buttercup"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
